added support for configuration definitions
ExpediaGroup/expediagroup-java-sdk pull request #10
Opened 2022-08-30 07:06 UTC by ayansen

### :pencil: Description
- 

### :link: Related Issues
-

2022-09-06 16:03 UTC, mohnoor94 requested changes

2022-09-06 16:03 UTC, mohnoor94 commented on src/main/kotlin/com/expediagroup/sdk/core/config/ConfigurationDefinition.kt
> +    /**
Please add appropriate docs for this and all non-private methods...

2022-09-06 16:03 UTC, mohnoor94 commented on src/main/kotlin/com/expediagroup/sdk/core/config/Configuration.kt
> +@Deprecated("we should be using the Config Class instead fo parse the values, the strongly typed objects can live with the respective modules")
_nit (a typo)_: ...instead fo...

2022-09-06 16:03 UTC, mohnoor94 commented on src/main/kotlin/com/expediagroup/sdk/core/config/Configuration.kt
> +    val configurationData: ConfigurationData,
Any reasons for why the properties are not private?

2022-09-06 16:03 UTC, mohnoor94 commented on src/main/kotlin/com/expediagroup/sdk/core/config/Configuration.kt
> + * @param configurationData deserialized configuration data which needs to be parsed
Please use the `@property` instead of `@param` for documenting the properties.

2022-09-06 16:03 UTC, mohnoor94 commented on src/main/kotlin/com/expediagroup/sdk/core/config/ConfigurationKey.kt
> +    data class Password(val password: String)
This looks like a good use case for a `value` class instead of a `data` class.

2022-09-06 20:34 UTC, ayansen commented on src/main/kotlin/com/expediagroup/sdk/core/config/Configuration.kt
> +    val configurationData: ConfigurationData,
nice catch! missed it

2022-09-06 21:50 UTC, ayansen commented on src/main/kotlin/com/expediagroup/sdk/core/config/ConfigurationKey.kt
> +    data class Password(val password: String)
ideally it should, for some reason Jacoco is not complying with value classes. Will look into that in a separate pr

2022-09-07 08:39 UTC, mohnoor94 approved these changes

2022-09-07 08:43 UTC, merged