chore: add contract test testcases generator
ExpediaGroup/expediagroup-java-sdk pull request #635
Opened 2024-07-23 16:38 UTC by OmarAlJarrah

### :pencil: Description
- 

### :link: Related Issues
-

2024-08-19 16:02 UTC, mohnoor94 requested changes

2024-08-19 16:02 UTC, mohnoor94 commented on .github/workflows/generate-contract-tests.yaml
> +      - name: Set up JDK 17
21

2024-08-19 16:02 UTC, mohnoor94 commented on .github/workflows/generate-contract-tests.yaml
> +          mvn clean install exec:java -Dexec.args="-i specs.yaml -o $output"
What is  "output" here?

2024-08-19 16:02 UTC, mohnoor94 commented on .github/workflows/generate-contract-tests.yaml
> +      specs_url:
Please use the new self-serve actions.

2024-08-19 16:02 UTC, mohnoor94 commented on sdk-test/src/main/kotlin/com/expediagroup/sdk/test/CLI.kt
> +            if (generateSdkTests) {
Let's use the early exit if here (`if not --> return`)

2024-08-19 16:02 UTC, mohnoor94 commented on sdk-test/src/main/kotlin/com/expediagroup/sdk/test/contract/Constant.kt
> +        "MAX_TEST_REQUEST_COMBINATIONS" to "1"
Looks like this is not needed.

2024-08-19 16:02 UTC, mohnoor94 commented on sdk-test/src/main/kotlin/com/expediagroup/sdk/test/contract/function/ExtractPathParamsFunc.kt
> +//            omar/google/(company:string)
???

2024-08-19 16:02 UTC, mohnoor94 commented on sdk-test/src/main/kotlin/com/expediagroup/sdk/test/contract/model/api/TestCaseHttpResponse.kt
> +                status = response.status
Shouldn't we compare the actual responses? (The data).

2024-08-19 16:02 UTC, mohnoor94 commented on sdk-test/src/main/kotlin/com/expediagroup/sdk/test/openapi/SdkTestGenerator.kt
> +            setTemplateDir("templates/expediagroup-sdk")
Let's take this as input.

2024-08-19 16:02 UTC, mohnoor94 commented on sdk-test/src/main/kotlin/com/expediagroup/sdk/test/openapi/SdkTestGenerator.kt
> +            addAdditionalProperty("shadePrefix", product.shadePrefix)
Let's remove the unneeded properties.

2024-08-19 21:21 UTC, OmarAlJarrah commented on sdk-test/src/main/kotlin/com/expediagroup/sdk/test/CLI.kt
> +            if (generateSdkTests) {
Done.

2024-08-19 21:21 UTC, OmarAlJarrah commented on sdk-test/src/main/kotlin/com/expediagroup/sdk/test/contract/Constant.kt
> +        "MAX_TEST_REQUEST_COMBINATIONS" to "1"
Done.

2024-08-20 10:06 UTC, OmarAlJarrah commented on .github/workflows/generate-contract-tests.yaml
> +      - name: Set up JDK 17
Removed the action as it no longer is needed.

2024-08-20 10:06 UTC, OmarAlJarrah commented on .github/workflows/generate-contract-tests.yaml
> +          mvn clean install exec:java -Dexec.args="-i specs.yaml -o $output"
Removed the action as it no longer is needed.

2024-08-20 10:06 UTC, OmarAlJarrah commented on .github/workflows/generate-contract-tests.yaml
> +      specs_url:
Removed the action as it no longer is needed.

2024-08-20 10:06 UTC, OmarAlJarrah commented on sdk-test/src/main/kotlin/com/expediagroup/sdk/test/contract/function/ExtractPathParamsFunc.kt
> +//            omar/google/(company:string)
Removed.

2024-08-20 10:06 UTC, OmarAlJarrah commented on sdk-test/src/main/kotlin/com/expediagroup/sdk/test/contract/model/api/TestCaseHttpResponse.kt
> +                status = response.status
Done.

2024-08-20 10:07 UTC, OmarAlJarrah commented on sdk-test/src/main/kotlin/com/expediagroup/sdk/test/openapi/SdkTestGenerator.kt
> +            setTemplateDir("templates/expediagroup-sdk")
Done,

2024-08-20 10:07 UTC, OmarAlJarrah commented on sdk-test/src/main/kotlin/com/expediagroup/sdk/test/openapi/SdkTestGenerator.kt
> +            addAdditionalProperty("shadePrefix", product.shadePrefix)
Done.

2024-08-28 14:34 UTC, anssari1 commented on sdk-test/src/main/kotlin/com/expediagroup/sdk/test/contract/model/api/TestCaseHttpRequest.kt
> +    /**
Remove dangling comments

2024-08-28 14:34 UTC, anssari1 commented on sdk-test/src/main/kotlin/com/expediagroup/sdk/test/contract/model/api/TestCaseHttpRequest.kt
> +    fun getRequestBody(): String? = if (hasBody()) body!! else null
Remove redundant !!

2024-08-28 14:34 UTC, anssari1 commented on sdk-test/src/main/resources/templates/expediagroup-sdk/executor.mustache
> +
Replace wild card imports

2024-08-28 14:50 UTC, OmarAlJarrah commented on sdk-test/src/main/kotlin/com/expediagroup/sdk/test/contract/model/api/TestCaseHttpRequest.kt
> +    fun getRequestBody(): String? = if (hasBody()) body!! else null
✅

2024-08-28 14:50 UTC, OmarAlJarrah commented on sdk-test/src/main/kotlin/com/expediagroup/sdk/test/contract/model/api/TestCaseHttpRequest.kt
> +    /**
✅

2024-08-28 14:50 UTC, OmarAlJarrah commented on sdk-test/src/main/resources/templates/expediagroup-sdk/executor.mustache
> +
✅

2024-08-28 14:51 UTC, anssari1 approved these changes

2024-08-28 15:38 UTC, mohnoor94 approved these changes
reviewed by Nasser

2024-08-28 15:38 UTC, merged